name: Build cv

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-cv:
    permissions:
      contents: write
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build PDF en
        run: latexmk ./cv-en.tex
      
      - name: Build PDF de
        run: latexmk ./cv-de.tex
      
      - name: Upload PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            cv-en.pdf
            cv-de.pdf