name: Build cv

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-cv:
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build PDF
        run: |-
          mkdir -p upload
          latexmk ./cv-en.tex
          latexmk ./cv-de.tex
          cp *.pdf upload/

      - uses: shallwefootball/upload-s3-action@v1.3.3
        name: Upload PDFs to S3
        with:
          aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          endpoint: ${{ secrets.S3_ENDPOINT }}
          source_dir: 'upload'
          destination_dir: ''