name: Build template

on:
  push:
    branches:
      - master
  pull_request:
  registry_package:

jobs:
  build-cv:
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PDF
        run: latexmk ./cv-en.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: cv-en.pdf
          path: ./cv-en.pdf

      - name: Upload log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cv-en.log
          path: ./cv-en.log